name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  container-build:
    name: Container Image Build (lab:${{ matrix.lab-version }} cuda:${{ matrix.cuda-version }}-${{ matrix.base-image }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lab-version: ["4.0.6"]
        base-image: ["runtime", "devel"]
        cuda-version: [ "12.1.1", "11.8.0" ]
        latest: "no"
        include:
          - lab-version: "4.0.6"
            cuda-version: "12.1.1"
            latest: "yes"
    steps:
      - uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: |
          echo "image_tag=lab-${{ matrix.lab-version }}-cuda-${{ matrix.cuda-version }}-${{ matrix.base-image }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: gpu-jupyter-qsim
          tags: latest ${{ steps.vars.outputs.image_tag }}
          containerfiles: |
            ./Containerfile
          build-args: |
            CUDA=${{ matrix.cuda-version }}
            BASE=${{ matrix.base-image }}
            LAB=${{ matrix.lab-version }}
          # workaround for https://github.com/pypa/pip/issues/11368
          extra-args: |
            --storage-opt=overlay.mount_program=

      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        if: github.ref == 'refs/heads/main'
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.vars.outputs.image_tag }}
          registry: quay.io/abn
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push To quay.io (latest tag)
        if: ${{ github.ref == 'refs/heads/main' && matrix.latest == 'yes' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: latest
          registry: quay.io/abn
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
